version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diversify
    volumes:
      - ~/dev/db_data/postgres/diversify:/var/lib/postgresql/data