app:
  source-filename:
    default: questions.csv
    languages:
      en: questions.csv
      ru: questions_ru.csv
  use-internalization: true

spring:
  messages:
    fallback-to-system-locale: false

logging:
  level:
    root: WARN