spring:
  datasource:
    url: jdbc:h2:file:~/.h2/library;AUTO_SERVER=TRUE # todo change to mem
    username: admin
    password: pass
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    show-sql: true
  sql:
    init:
      mode: embedded
      schema-locations: schema.sql
      data-locations: data.sql
  h2:
    console:
      path: /h2-console
      enabled: true
  output:
    ansi:
      enabled: always

logging:
  level:
    ru: DEBUG