
spring:
  datasource:
    url: jdbc:h2:mem:library
    username: admin
    password: pass
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql

logging:
    level:
      ru: DEBUG