server:
  port: 8020

spring:
  application:
    name: diversify-visualizer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8005/eureka}
    fetch-registry: false
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseExpirationDurationInSeconds: 90
    leaseRenewalIntervalInSeconds: 30
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true